### PR TITLE
Update main to have more vmem

### PR DESCRIPTION
**Pull request by bacaron**

### CODE REVIEW

**Comment by skoudoro** [comment]
Hi @bacaron, this repo is deprecated,  which apps is using it ?

**Comment by bacaron** [comment]
@skoudoro ,

The Median Otsu mask generatoin app: https://brainlife.io/app/5a5100c306b9e8003f1ee684 is still pointing to this repo and branch.

Thanks,
Brad

**Comment by skoudoro** [comment]
Thank you for this info @bacaron! We need to update that. @guaje, can you look at this ?

**Comment by guaje** [comment]
Sure, do you want me to create independent repos for: median otsu, recobundles, reslice, and info?

**Comment by skoudoro** [comment]
yes, new individual repo like the others, I do not know why I did not do it before.... that is strange...

Thanks!

**Comment by bacaron** [comment]
Thank you @skoudoro and @guaje! I appreciate all of the hard work and help with these!

**Pull request merged**
